# Generated by Django 2.1.7 on 2019-07-18 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('photo', models.ImageField(blank=True, upload_to='feed_photos')),
                ('category', models.CharField(max_length=256)),
                ('PBstore', models.CharField(max_length=256)),
                ('rating', models.FloatField(blank=True, default=None, null=True)),
                ('num_rating', models.IntegerField(default=0)),
                ('rank_point', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
