# Generated by Django 2.1.7 on 2019-07-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PBstore',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
