# Generated by Django 2.1.7 on 2019-07-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_auto_20190720_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='PBstore',
        ),
        migrations.RemoveField(
            model_name='product',
            name='emoticon',
        ),
    ]
