# Generated by Django 2.1.7 on 2019-07-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0004_auto_20190720_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PBstore',
            field=models.ImageField(blank=True, upload_to='store_photos'),
        ),
    ]
