# Generated by Django 2.1.7 on 2019-07-19 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0005_product_pbstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rank_point']},
        ),
    ]
