# Generated by Django 2.1.7 on 2019-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0008_auto_20190720_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='emoticon',
            field=models.ImageField(blank=True, default='https://image.flaticon.com/icons/png/128/1742/1742384.png', upload_to='products_photos'),
        ),
    ]
