# Generated by Django 2.1.7 on 2019-07-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0005_auto_20190713_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='review',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='saved_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='liked_users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='save',
            name='product',
        ),
        migrations.RemoveField(
            model_name='save',
            name='user',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Save',
        ),
    ]
