# Generated by Django 2.1.7 on 2019-07-20 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewpage', '0006_auto_20190720_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.CharField(max_length=256)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('category_code', models.CharField(choices=[('00', 'undefined'), ('10', 'icecream'), ('11', 'icecream_bar'), ('12', 'icecream_cone'), ('20', 'liquid'), ('21', 'liquid_coffee'), ('22', 'liquid_dairy'), ('23', 'liquid_soda'), ('30', 'snack'), ('40', 'sweets'), ('41', 'sweets_chocolate'), ('42', 'sweets_candy'), ('43', 'sweets_gum'), ('44', 'sweets_jelly'), ('50', 'convenient'), ('51', 'convenient_gimbab'), ('52', 'convenient_sandwich'), ('53', 'convenient_dosirak'), ('60', 'ramen'), ('70', 'alcohol'), ('71', 'alcohol_beer'), ('72', 'alcohol_soju'), ('80', 'bread/dessert'), ('81', 'dessert_bread'), ('82', 'dessert_cake'), ('90', 'etc')], max_length=2)),
                ('pb_store_code', models.CharField(choices=[('0', 'is_not_pb'), ('1', 'cu'), ('2', 'gs25'), ('3', 'emart24'), ('4', 'seveneleven'), ('5', 'ministop')], max_length=1)),
                ('emoticon', models.ImageField(blank=True, default='https://image.flaticon.com/icons/png/128/1742/1742384.png', upload_to='products_photos')),
                ('rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('num_rating', models.IntegerField(default=0)),
                ('rank_point', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-rank_point'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('review_rating', models.IntegerField(choices=[(1, '우웩'), (2, '노맛'), (3, '그닥'), (4, '맛나'), (5, '꿀맛')])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='review_photos')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('liked_users', models.ManyToManyField(blank=True, related_name='reviews_liked', through='reviewpage.Like', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewpage.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewpage.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='saved_users',
            field=models.ManyToManyField(blank=True, related_name='products_saved', through='reviewpage.Save', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewpage.Review'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
