# Generated by Django 2.1.7 on 2019-07-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0008_remove_product_num_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-updated_at']},
        ),
    ]
