# Generated by Django 2.2 on 2019-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0009_auto_20190726_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emoticon',
            field=models.ImageField(blank=True, default='https://image.flaticon.com/icons/png/128/1742/1742384.png', upload_to='products_photos'),
        ),
    ]
