# Generated by Django 2.2 on 2019-08-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0012_remove_review_emoticon'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emoticon',
            field=models.ImageField(blank=True, default='https://image.flaticon.com/icons/png/128/1742/1742384.png', upload_to=''),
        ),
    ]
