# Generated by Django 2.2 on 2019-08-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0013_review_emoticon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='emoticon',
        ),
    ]
