# Generated by Django 2.1.7 on 2019-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0018_auto_20190817_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pb_store_code',
            field=models.CharField(choices=[('0', 'is_not_pb'), ('1', 'cu'), ('2', 'gs25'), ('3', 'emart24'), ('4', 'seveneleven'), ('5', 'ministop')], max_length=1),
        ),
    ]
